# Generated by Django 5.2 on 2025-06-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_word', models.CharField(max_length=100, unique=True)),
                ('partner1_name', models.CharField(max_length=50)),
                ('partner2_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mode', models.CharField(choices=[('questions', 'Questions'), ('truth', 'Truth or Dare'), ('challenge', 'Challenge'), ('spicy', 'Spicy Only'), ('mixed', 'Mixed Mode'), ('would', 'Would You Rather')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mode', models.CharField(choices=[('questions', 'Questions'), ('truth', 'Truth or Dare'), ('challenge', 'Challenge'), ('spicy', 'Spicy Only'), ('mixed', 'Mixed Mode'), ('would', 'Would You Rather')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.couplesession')),
            ],
        ),
    ]
