# Generated by Django 5.2 on 2025-06-18 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_load_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplesession',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='couplesession',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='couplesession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='couplesession',
            name='partner1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='couplesession',
            name='partner2_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='couplesession',
            name='secret_word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='couplesession',
            unique_together={('partner1_name', 'partner2_name', 'secret_word')},
        ),
    ]
