# Generated by Django 5.2 on 2025-06-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_load_questions'),
        ('game', '0002_playedquestion'),
    ]

    operations = [
    ]
